# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='cn',
            field=models.CharField(default='default', max_length=80, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
